Update requirements.txt
Generation-for-Financial-data/Financial-Imbalanced-Data-With-Deep-Density-Hybrid-Sampling pull request #2
Opened 2023-07-21 02:34 UTC by Jangsehawn

## What does this PR do?

## How to test this? 
- 

## Does anything else need to be done?
-

2023-07-21 05:24 UTC, RektPunk requested changes
확인부탁드립니다

2023-07-21 05:24 UTC, RektPunk commented on requirements.txt
> +# 회사 패키지 버전 12003
```suggestion
# 회사 패키지 버전
```

2023-07-21 05:24 UTC, RektPunk commented on requirements.txt
> +# 회사 패키지 버전 12003
숫자 없어도 될것 같습니다

2023-07-21 05:24 UTC, RektPunk commented on requirements.txt
> +# pytorch-lightining == 1.2.10 -> 없음
```suggestion
```

2023-07-21 05:24 UTC, RektPunk commented on requirements.txt
> +# pytorch-lightining == 1.2.10 -> 없음
없으면 빼주시는게 좋을것 같아요

2023-07-22 04:57 UTC, Jangsehawn reviewed
확인했습니다!

2023-07-23 02:52 UTC, RektPunk approved these changes

2023-07-23 02:52 UTC, merged

2023-07-23 02:57 UTC, RektPunk commented
고생하셨습니다 :)